spring:
  application:
    name: ProjectBankSystem

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always
      schema-locations: classpath:db/init.sql
      data-locations: classpath:db/data.sql

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect