spring:
  application:
    name: ProjectBankSystem

  datasource:
    url: jdbc:mysql://localhost:3306/servi
    username: root
    password: 123123

  sql:
    init:
      mode: always
      schema-locations: classpath:db/init.sql
      data-locations: classpath:db/data.sql

  jpa:
    hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect